/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package examenjava2;

import net.datafaker.Faker;
import java.util.ArrayList;

import com.google.common.collect.Queues;
import com.kevinolarte.Paciente;


import java.util.Stack;  //Pila
import java.util.ArrayList; //ArrayList
import java.util.Queue;  //Cola
import java.util.LinkedList;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Queue<Integer> cola = new LinkedList();
        cola.add(1);
        cola.add(2);
        cola.add(3);
        System.out.println(cola.remove());
        System.out.println(cola.remove());
        System.out.println(cola.remove());
        System.out.println(cola.remove());
       
       
        
    }
}
