/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package examenjava2;

import net.datafaker.Faker;

import java.sql.Time;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.ArrayList;

import com.google.common.collect.Queues;
import com.kevinolarte.centroMedico.Ejercicio7;
import com.kevinolarte.centroMedico.Paciente;

import lib.Fakers;
import lib.Fechas;

import java.util.Stack;  //Pila
import java.util.ArrayList; //ArrayList
import java.util.Queue;  //Cola
import java.util.LinkedList;


public class App {
    public static void main(String[] args) {
       System.out.println(Fechas.obtenerFecha());
    }
}
